app = 'aprs-dashboard-frontend'
primary_region = 'iad'

[build]
  [build.args]
    NEXT_PUBLIC_BACKEND_URL = "https://aprs-dashboard-backend.fly.dev"
    NEXT_PUBLIC_BASE_URL = "https://aprs-dashboard-frontend.fly.dev"

[http_service]
  internal_port = 7530
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
